# Site settings
title: Kenny Fraser
email: me@kennyfraser.com
description: Kenny Fraser is a freelance web designer, developer and marketer living in the Scottish Highlands.
# >  this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kennyfraser.com" # the base hostname & protocol for your site
twitter_username: kennyfraser
github_username:  kennyifraser

# Build settings
markdown: kramdown
