# Site settings
title: Kenny Fraser
description: Kenny Fraser is a freelance Web Designer and Front End Web Developer living near Inverness in the Scottish Highlands.
# >  this means to ignore newlines until "baseurl:"
baseurl: ""                     # the subpath of your site, e.g. /blog/
url: "http://kennyfraser.com"   # the base hostname & protocol for your site

# Build settings
markdown: kramdown
sass:
    style: compressed

# Ruby Gems
gems:
  - jekyll-sitemap
  # - octopress-minify-html